//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ReportingServices.ReportProcessing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RDLValidatingReaderStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDLValidatingReaderStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ReportingServices.ReportProcessing.RDLValidatingReaderStrings", typeof(RDLValidatingReaderStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report definition element &apos;{0}&apos; contains more than one child element of type &apos;{1}&apos; at line {2}, position {3}..
        /// </summary>
        internal static string rdlValidationInvalidElement {
            get {
                return ResourceManager.GetString("rdlValidationInvalidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is not valid within the element {1}. &apos;{0}&apos; at line {2}, position {3}..
        /// </summary>
        internal static string rdlValidationInvalidMicroVersionedAttribute {
            get {
                return ResourceManager.GetString("rdlValidationInvalidMicroVersionedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; is not valid within the parent element {1}. &apos;{0}&apos; at line {2}, position {3}..
        /// </summary>
        internal static string rdlValidationInvalidMicroVersionedElement {
            get {
                return ResourceManager.GetString("rdlValidationInvalidMicroVersionedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is not a valid Rdl attribute. Attributes in the namespace &apos;{1}&apos; are not allowed. &apos;{0}&apos; at line {2}, position {3}..
        /// </summary>
        internal static string rdlValidationInvalidNamespaceAttribute {
            get {
                return ResourceManager.GetString("rdlValidationInvalidNamespaceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; is not a valid Rdl element. Elements in the namespace &apos;{1}&apos; are not allowed. &apos;{0}&apos; at line {2}, position {3}..
        /// </summary>
        internal static string rdlValidationInvalidNamespaceElement {
            get {
                return ResourceManager.GetString("rdlValidationInvalidNamespaceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report definition element &apos;{0}&apos; in namespace &apos;{1}&apos; has an invalid parent &apos;{2}&apos; at line {3}, position {4}..
        /// </summary>
        internal static string rdlValidationInvalidParent {
            get {
                return ResourceManager.GetString("rdlValidationInvalidParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report definition element &apos;{0}&apos; is empty at line {2}, position {3}. It is missing a mandatory child element of type &apos;{1}&apos;..
        /// </summary>
        internal static string rdlValidationMissingChildElement {
            get {
                return ResourceManager.GetString("rdlValidationMissingChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefixes &apos;{0}&apos; inside attribute &apos;{1}&apos; have no defined schema at line {2} position {3}..
        /// </summary>
        internal static string rdlValidationMultipleUndefinedSchemaNamespaces {
            get {
                return ResourceManager.GetString("rdlValidationMultipleUndefinedSchemaNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No declaration found for the report definition element &apos;{0}&apos; at line {3}, in the namespace {2}. Please reconsider the correct namespace for the element &apos;{1}&apos; and modify the element with the appropriate prefix..
        /// </summary>
        internal static string rdlValidationNoElementDecl {
            get {
                return ResourceManager.GetString("rdlValidationNoElementDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix &apos;{0}&apos; inside attribute &apos;{1}&apos; has no defined schema at line {2} position {3}..
        /// </summary>
        internal static string rdlValidationUndefinedSchemaNamespace {
            get {
                return ResourceManager.GetString("rdlValidationUndefinedSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; with prefix &apos;{1}&apos; is requred but not known by {2} at line {3} position {4}..
        /// </summary>
        internal static string rdlValidationUnknownRequiredNamespaces {
            get {
                return ResourceManager.GetString("rdlValidationUnknownRequiredNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema {0} with prefix &apos;{1}&apos; at line {2}, position {3} is not supported by this version of Reporting Services. .
        /// </summary>
        internal static string rdlValidationUnsupportedSchema {
            get {
                return ResourceManager.GetString("rdlValidationUnsupportedSchema", resourceCulture);
            }
        }
    }
}
